name: xftts_fluttify
description: A `xftts` flutter plugin, Powered by `Fluttify` engine.
version: 0.0.1
author: yohom <382146139@qq.com>
homepage: https://github.com/fluttify-project/xftts_fluttify

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.fluttify.xftts_fluttify
    pluginClass: XfttsFluttifyPlugin